1. What is the difference between a Series and a Dataframe.
- Series is 1-Dimensional array that can hold data of any type while Dataframe is 2-Dimensional data structure that hold data like a 2-d array or a table

In [10]:
import pandas as pd
import numpy as np

In [11]:
serie=pd.Series([1,3,4,5,6],name="seiries",index=[10,12,14,16,18],dtype=int)
print(type(serie))
serie

<class 'pandas.core.series.Series'>

10    1
12    3
14    4
16    5
18    6
Name: seiries, dtype: int32

In [12]:
import pandas as pd

df = pd.DataFrame({
    "student_id": [1, 2, 3],
    "student_name": ["Ali", "Salim", "Mahaba"]
})

print(type(df))
print(df)

<class 'pandas.core.frame.DataFrame'>
   student_id student_name
0           1          Ali
1           2        Salim
2           3       Mahaba

### Column Selection,Addition and Deletion

In [13]:
new_df=pd.DataFrame({
    "student_id": range(1, 16),
    "name": ["Ali", "Salim", "Mahaba", "Sara", "John", "NaN", "Ella", "Mike", "Nina", "Tom", "Lucas", "NaN", "Zara", "Omar", "Leo"],
    "age": [20, 21, np.nan, 22, 23, np.nan, 24, 25, 26, 22, 21, 20, np.nan, 27, 24],
    "grade": ["A", "B", np.nan, "A", "C", "A", "B", "C", "A", "B", "C", "A", "B", "C", "A"],
    "enrollment_date": pd.date_range(start='2023-01-01', periods=15).tolist()
})
new_df

    student_id    name   age grade enrollment_date
0            1     Ali  20.0     A      2023-01-01
1            2   Salim  21.0     B      2023-01-02
2            3  Mahaba   NaN   NaN      2023-01-03
3            4    Sara  22.0     A      2023-01-04
4            5    John  23.0     C      2023-01-05
5            6     NaN   NaN     A      2023-01-06
6            7    Ella  24.0     B      2023-01-07
7            8    Mike  25.0     C      2023-01-08
8            9    Nina  26.0     A      2023-01-09
9           10     Tom  22.0     B      2023-01-10
10          11   Lucas  21.0     C      2023-01-11
11          12     NaN  20.0     A      2023-01-12
12          13    Zara   NaN     B      2023-01-13
13          14    Omar  27.0     C      2023-01-14
14          15     Leo  24.0     A      2023-01-15

In [14]:
# Selecting a column and row
col1=new_df["name"] # Select 2nd column
print(col1)
row2=new_df.iloc[5:10] #selects 4th-9th row
print(row2)

0        Ali
1      Salim
2     Mahaba
3       Sara
4       John
5        NaN
6       Ella
7       Mike
8       Nina
9        Tom
10     Lucas
11       NaN
12      Zara
13      Omar
14       Leo
Name: name, dtype: object
   student_id  name   age grade enrollment_date
5           6   NaN   NaN     A      2023-01-06
6           7  Ella  24.0     B      2023-01-07
7           8  Mike  25.0     C      2023-01-08
8           9  Nina  26.0     A      2023-01-09
9          10   Tom  22.0     B      2023-01-10

In [15]:
# Addition
#adding columns
# Adding a new column 'gender'
new_df['gender'] = ['M', 'M', 'F', 'F', 'M', 'F', 'F', 'M', 'F', 'M', 'M', 'F', 'F', 'M', 'M']

print(new_df)
# Adding a new row
# Adding a new row using pd.concat
new_row_df = pd.DataFrame([{'student_id': 16, 'name': 'Emma', 'age': 23, 'grade': 'A', 'enrollment_date': '2023-09-01', 'gender': 'F'}])
new_df = pd.concat([new_df, new_row_df], ignore_index=True)

print(df)

print(new_df)

    student_id    name   age grade enrollment_date gender
0            1     Ali  20.0     A      2023-01-01      M
1            2   Salim  21.0     B      2023-01-02      M
2            3  Mahaba   NaN   NaN      2023-01-03      F
3            4    Sara  22.0     A      2023-01-04      F
4            5    John  23.0     C      2023-01-05      M
5            6     NaN   NaN     A      2023-01-06      F
6            7    Ella  24.0     B      2023-01-07      F
7            8    Mike  25.0     C      2023-01-08      M
8            9    Nina  26.0     A      2023-01-09      F
9           10     Tom  22.0     B      2023-01-10      M
10          11   Lucas  21.0     C      2023-01-11      M
11          12     NaN  20.0     A      2023-01-12      F
12          13    Zara   NaN     B      2023-01-13      F
13          14    Omar  27.0     C      2023-01-14      M
14          15     Leo  24.0     A      2023-01-15      M
   student_id student_name
0           1          Ali
1           2        Salim
2           3       Mahaba
    student_id    name   age grade      enrollment_date gender
0            1     Ali  20.0     A  2023-01-01 00:00:00      M
1            2   Salim  21.0     B  2023-01-02 00:00:00      M
2            3  Mahaba   NaN   NaN  2023-01-03 00:00:00      F
3            4    Sara  22.0     A  2023-01-04 00:00:00      F
4            5    John  23.0     C  2023-01-05 00:00:00      M
5            6     NaN   NaN     A  2023-01-06 00:00:00      F
6            7    Ella  24.0     B  2023-01-07 00:00:00      F
7            8    Mike  25.0     C  2023-01-08 00:00:00      M
8            9    Nina  26.0     A  2023-01-09 00:00:00      F
9           10     Tom  22.0     B  2023-01-10 00:00:00      M
10          11   Lucas  21.0     C  2023-01-11 00:00:00      M
11          12     NaN  20.0     A  2023-01-12 00:00:00      F
12          13    Zara   NaN     B  2023-01-13 00:00:00      F
13          14    Omar  27.0     C  2023-01-14 00:00:00      M
14          15     Leo  24.0     A  2023-01-15 00:00:00      M
15          16    Emma  23.0     A           2023-09-01      F

In [16]:
print(new_df.iloc[:,1])# Accessing name column using its index
print(new_df.loc[0:15,["name"]])

0        Ali
1      Salim
2     Mahaba
3       Sara
4       John
5        NaN
6       Ella
7       Mike
8       Nina
9        Tom
10     Lucas
11       NaN
12      Zara
13      Omar
14       Leo
15      Emma
Name: name, dtype: object
      name
0      Ali
1    Salim
2   Mahaba
3     Sara
4     John
5      NaN
6     Ella
7     Mike
8     Nina
9      Tom
10   Lucas
11     NaN
12    Zara
13    Omar
14     Leo
15    Emma

In [17]:
print(new_df.iloc[2:6,])#select all column from row 2 to 5

   student_id    name   age grade      enrollment_date gender
2           3  Mahaba   NaN   NaN  2023-01-03 00:00:00      F
3           4    Sara  22.0     A  2023-01-04 00:00:00      F
4           5    John  23.0     C  2023-01-05 00:00:00      M
5           6     NaN   NaN     A  2023-01-06 00:00:00      F

### Handling Missing Data

In [18]:
new_df.isna() #Returns boolean value for evry attribute with true for missing

    student_id   name    age  grade  enrollment_date  gender
0        False  False  False  False            False   False
1        False  False  False  False            False   False
2        False  False   True   True            False   False
3        False  False  False  False            False   False
4        False  False  False  False            False   False
5        False  False   True  False            False   False
6        False  False  False  False            False   False
7        False  False  False  False            False   False
8        False  False  False  False            False   False
9        False  False  False  False            False   False
10       False  False  False  False            False   False
11       False  False  False  False            False   False
12       False  False   True  False            False   False
13       False  False  False  False            False   False
14       False  False  False  False            False   False
15       False  False  False  False            False   False

In [19]:
new_df.notnull() #Returns boolean value for evry attribute with false for missing

    student_id  name    age  grade  enrollment_date  gender
0         True  True   True   True             True    True
1         True  True   True   True             True    True
2         True  True  False  False             True    True
3         True  True   True   True             True    True
4         True  True   True   True             True    True
5         True  True  False   True             True    True
6         True  True   True   True             True    True
7         True  True   True   True             True    True
8         True  True   True   True             True    True
9         True  True   True   True             True    True
10        True  True   True   True             True    True
11        True  True   True   True             True    True
12        True  True  False   True             True    True
13        True  True   True   True             True    True
14        True  True   True   True             True    True
15        True  True   True   True             True    True

In [20]:
new_df.isnull().sum()

student_id         0
name               0
age                3
grade              1
enrollment_date    0
gender             0
dtype: int64

In [21]:
new_df.info # info Also shows where the data is missing. Suitable for small sets

<bound method DataFrame.info of     student_id    name   age grade      enrollment_date gender
0            1     Ali  20.0     A  2023-01-01 00:00:00      M
1            2   Salim  21.0     B  2023-01-02 00:00:00      M
2            3  Mahaba   NaN   NaN  2023-01-03 00:00:00      F
3            4    Sara  22.0     A  2023-01-04 00:00:00      F
4            5    John  23.0     C  2023-01-05 00:00:00      M
5            6     NaN   NaN     A  2023-01-06 00:00:00      F
6            7    Ella  24.0     B  2023-01-07 00:00:00      F
7            8    Mike  25.0     C  2023-01-08 00:00:00      M
8            9    Nina  26.0     A  2023-01-09 00:00:00      F
9           10     Tom  22.0     B  2023-01-10 00:00:00      M
10          11   Lucas  21.0     C  2023-01-11 00:00:00      M
11          12     NaN  20.0     A  2023-01-12 00:00:00      F
12          13    Zara   NaN     B  2023-01-13 00:00:00      F
13          14    Omar  27.0     C  2023-01-14 00:00:00      M
14          15     Leo  24.0     A  2023-01-15 00:00:00      M
15          16    Emma  23.0     A           2023-09-01      F>

In [22]:
has_missing = new_df.isnull().any() # Use any to check if column has any missing value
print(has_missing)

student_id         False
name               False
age                 True
grade               True
enrollment_date    False
gender             False
dtype: bool

In [23]:
non_missing=new_df.dropna(axis=0,how='any')
non_missing

    student_id   name   age grade      enrollment_date gender
0            1    Ali  20.0     A  2023-01-01 00:00:00      M
1            2  Salim  21.0     B  2023-01-02 00:00:00      M
3            4   Sara  22.0     A  2023-01-04 00:00:00      F
4            5   John  23.0     C  2023-01-05 00:00:00      M
6            7   Ella  24.0     B  2023-01-07 00:00:00      F
7            8   Mike  25.0     C  2023-01-08 00:00:00      M
8            9   Nina  26.0     A  2023-01-09 00:00:00      F
9           10    Tom  22.0     B  2023-01-10 00:00:00      M
10          11  Lucas  21.0     C  2023-01-11 00:00:00      M
11          12    NaN  20.0     A  2023-01-12 00:00:00      F
13          14   Omar  27.0     C  2023-01-14 00:00:00      M
14          15    Leo  24.0     A  2023-01-15 00:00:00      M
15          16   Emma  23.0     A           2023-09-01      F

In [24]:
filled=new_df.fillna(67)

In [25]:
data = {
    'A': [1, 2, np.nan, 4],
    'B': [np.nan, 5, np.nan, 6],
    'C': [7, 8, 9, np.nan]
}

df = pd.DataFrame(data)

print("Original DataFrame:\n", df)

# 1. Fill NaNs with a specific value
df_filled_value = df.fillna(0)
print("\nFilled NaNs with 0:\n", df_filled_value)

# 2. Forward fill NaNs
df_filled_ffill = df.fillna(method='ffill')
print("\nForward filled NaNs:\n", df_filled_ffill)

# 3. Backward fill NaNs
df_filled_bfill = df.fillna(method='bfill')
print("\nBackward filled NaNs:\n", df_filled_bfill)

# 4. Fill along columns
df_filled_axis = df.fillna(value=10, axis=1)  # Fill NaNs in all columns with 10
print("\nFilled NaNs along columns with 10:\n", df_filled_axis)

# 5. Limit the number of NaNs to fill
df_filled_limit = df.fillna(method='ffill', limit=1)  # Fill only the first NaN in consecutive NaNs
print("\nForward fill with limit of 1:\n", df_filled_limit)

# 6. Fill in place
df.fillna(0, inplace=True)
print("\nOriginal DataFrame after filling NaNs in place with 0:\n", df)

Original DataFrame:
      A    B    C
0  1.0  NaN  7.0
1  2.0  5.0  8.0
2  NaN  NaN  9.0
3  4.0  6.0  NaN

Filled NaNs with 0:
      A    B    C
0  1.0  0.0  7.0
1  2.0  5.0  8.0
2  0.0  0.0  9.0
3  4.0  6.0  0.0

Forward filled NaNs:
      A    B    C
0  1.0  NaN  7.0
1  2.0  5.0  8.0
2  2.0  5.0  9.0
3  4.0  6.0  9.0

Backward filled NaNs:
      A    B    C
0  1.0  5.0  7.0
1  2.0  5.0  8.0
2  4.0  6.0  9.0
3  4.0  6.0  NaN

Filled NaNs along columns with 10:
       A     B     C
0   1.0  10.0   7.0
1   2.0   5.0   8.0
2  10.0  10.0   9.0
3   4.0   6.0  10.0

Forward fill with limit of 1:
      A    B    C
0  1.0  NaN  7.0
1  2.0  5.0  8.0
2  2.0  5.0  9.0
3  4.0  6.0  9.0

Original DataFrame after filling NaNs in place with 0:
      A    B    C
0  1.0  0.0  7.0
1  2.0  5.0  8.0
2  0.0  0.0  9.0
3  4.0  6.0  0.0

C:\Users\mahab\AppData\Local\Temp\ipykernel_13936\3404602104.py:16: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_filled_ffill = df.fillna(method='ffill')
C:\Users\mahab\AppData\Local\Temp\ipykernel_13936\3404602104.py:20: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_filled_bfill = df.fillna(method='bfill')
C:\Users\mahab\AppData\Local\Temp\ipykernel_13936\3404602104.py:28: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_filled_limit = df.fillna(method='ffill', limit=1)  # Fill only the first NaN in consecutive NaNs

### Duplicates

In [26]:
new_df.duplicated()# Returns boolean value for each row

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
dtype: bool

In [27]:
new_df.duplicated().sum()# Returns Number of rows with duplicates

0

In [28]:
new_df.index.is_unique # returns boolean value checking whether if rows are unique

True

In [29]:
# Removing duplicates
new_df.drop_duplicates(keep='first')

    student_id    name   age grade      enrollment_date gender
0            1     Ali  20.0     A  2023-01-01 00:00:00      M
1            2   Salim  21.0     B  2023-01-02 00:00:00      M
2            3  Mahaba   NaN   NaN  2023-01-03 00:00:00      F
3            4    Sara  22.0     A  2023-01-04 00:00:00      F
4            5    John  23.0     C  2023-01-05 00:00:00      M
5            6     NaN   NaN     A  2023-01-06 00:00:00      F
6            7    Ella  24.0     B  2023-01-07 00:00:00      F
7            8    Mike  25.0     C  2023-01-08 00:00:00      M
8            9    Nina  26.0     A  2023-01-09 00:00:00      F
9           10     Tom  22.0     B  2023-01-10 00:00:00      M
10          11   Lucas  21.0     C  2023-01-11 00:00:00      M
11          12     NaN  20.0     A  2023-01-12 00:00:00      F
12          13    Zara   NaN     B  2023-01-13 00:00:00      F
13          14    Omar  27.0     C  2023-01-14 00:00:00      M
14          15     Leo  24.0     A  2023-01-15 00:00:00      M
15          16    Emma  23.0     A           2023-09-01      F